# Generated by Django 5.2.9 on 2025-12-28 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DirKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Directory kind name (e.g., 'LOCAL', 'BACKUP')",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Directory Kind",
                "verbose_name_plural": "Directory Kinds",
                "db_table": "DirKinds",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "Locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Full path to the directory",
                        max_length=2048,
                        unique=True,
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        help_text="Last modification time of the directory"
                    ),
                ),
                ("mirror", models.IntegerField(help_text="Mirror status indicator")),
                (
                    "kind",
                    models.ForeignKey(
                        help_text="Directory kind/category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directories",
                        to="catalog.dirkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Directory",
                "verbose_name_plural": "Directories",
                "db_table": "Directories",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Hash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Full path to the photo file",
                        max_length=2048,
                        unique=True,
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        help_text="MD5 hash of the file (32 characters)",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hash must be a 32-character hexadecimal string",
                                regex="^[a-f0-9]{32}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Hash",
                "verbose_name_plural": "Photo Hashes",
                "db_table": "Hash",
                "ordering": ["path"],
                "indexes": [models.Index(fields=["hash"], name="Hash_hash_193583_idx")],
            },
        ),
        migrations.CreateModel(
            name="TimeLoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Timestamp associated with the directory"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location associated with the directory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_locs",
                        to="catalog.location",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        help_text="Directory path",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_locs",
                        to="catalog.directory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Location",
                "verbose_name_plural": "Time Locations",
                "db_table": "TimeLoc",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(fields=["kind"], name="Directories_kind_id_6bd589_idx"),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["last_modified"], name="Directories_last_mo_d8d38e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeloc",
            index=models.Index(fields=["timestamp"], name="TimeLoc_timesta_2ee691_idx"),
        ),
        migrations.AddIndex(
            model_name="timeloc",
            index=models.Index(fields=["location"], name="TimeLoc_locatio_a69a49_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="timeloc",
            unique_together={("path", "timestamp", "location")},
        ),
    ]
