# Generated by Django 5.2.9 on 2026-04-15 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_hash_to_checksum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checksum",
            options={
                "ordering": ["path"],
                "verbose_name": "Photo Checksum",
                "verbose_name_plural": "Photo Checksums",
            },
        ),
        migrations.RemoveIndex(
            model_name="checksum",
            name="Hash_hash_193583_idx",
        ),
        migrations.AlterField(
            model_name="checksum",
            name="checksum",
            field=models.CharField(
                help_text="Checksum of the file (32 hex characters)",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Checksum must be a 32-character hexadecimal string",
                        regex="^[a-f0-9]{32}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="checksum",
            index=models.Index(fields=["checksum"], name="Hash_checksu_f3ec51_idx"),
        ),
    ]
