# Generated by Django 5.2.9 on 2025-12-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photograph", "0005_remove_photograph_image_photograph_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("DELETE", "Delete")],
                        help_text="Type of action to be performed",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the planned action was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the planned action was last updated",
                    ),
                ),
                (
                    "photograph",
                    models.ForeignKey(
                        help_text="Photograph this action applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_actions",
                        to="photograph.photograph",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planned Action",
                "verbose_name_plural": "Planned Actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_type"], name="planner_pla_action__cf468d_idx"
                    ),
                    models.Index(
                        fields=["photograph"], name="planner_pla_photogr_09d31b_idx"
                    ),
                ],
            },
        ),
    ]
