# Generated by Django 5.2.15 on 2026-09-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0001_initial"),
        ("photograph", "0009_rename_photograph_hash_to_checksum"),
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedaction",
            name="organizer_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_actions",
                to="organizer.organizerjob",
            ),
        ),
        migrations.AlterField(
            model_name="plannedaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("DELETE", "Delete"),
                    ("ORGANIZE", "Organize"),
                    ("RETRY", "Retry"),
                ],
                help_text="Type of action to be performed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plannedaction",
            name="photograph",
            field=models.ForeignKey(
                blank=True,
                help_text="Photograph this action applies to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_actions",
                to="photograph.photograph",
            ),
        ),
    ]
