# Generated by Django 5.2.17 on 2026-09-30 10:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


def populate_idempotency_keys(apps, schema_editor):
    PlannedAction = apps.get_model("planner", "PlannedAction")
    for action in PlannedAction.objects.filter(idempotency_key__isnull=True):
        action.idempotency_key = uuid.uuid4()
        action.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0005_duplicategroup_configuration_and_more"),
        ("photograph", "0009_rename_photograph_hash_to_checksum"),
        ("planner", "0002_plannedaction_organizer_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedaction",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="idempotency_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_idempotency_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="plannedaction",
            name="idempotency_key",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="organizer_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planned_actions",
                to="organizer.organizerconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="result_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resulting_planned_actions",
                to="organizer.organizerjob",
            ),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plannedaction",
            name="task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="plannedaction",
            name="photograph",
            field=models.ForeignKey(
                blank=True,
                help_text="Photograph this action applies to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planned_actions",
                to="photograph.photograph",
            ),
        ),
    ]
