"""
Django settings for backend project - Production (most restrictive base).

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# ALLOWED_HOSTS: derive from DOMAIN if not explicitly set
# DOMAIN can be a single domain or comma-separated list
domain = config("DOMAIN", default="")
if domain:
    ALLOWED_HOSTS = [d.strip() for d in domain.split(",") if d.strip()]
else:
    # Fallback to explicit ALLOWED_HOSTS if DOMAIN not set
    ALLOWED_HOSTS = config(
        "ALLOWED_HOSTS",
        default="",
        cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "album",
    "catalog",
    "photograph",
    "planner",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Determine engine based on whether DB credentials are provided
# If DB_USER is set, assume PostgreSQL; otherwise use SQLite
db_user = config("DB_USER", default="")
if db_user:
    # PostgreSQL configuration
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="photochart"),
            "USER": db_user,
            "PASSWORD": config("DB_PASSWORD", default=""),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }
else:
    # SQLite configuration
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": config("DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = "media/"
MEDIA_ROOT = config("MEDIA_ROOT", default=BASE_DIR / "media", cast=Path)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings - always derive from ALLOWED_HOSTS (most restrictive)
CORS_ALLOWED_ORIGINS = (
    [f"https://{host}" for host in ALLOWED_HOSTS]
    + [f"http://{host}" for host in ALLOWED_HOSTS]
    if ALLOWED_HOSTS
    else []
)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "content-type",
    "accept",
    "authorization",
    "x-csrftoken",
]

CSRF_TRUSTED_ORIGINS = [
    cors_origin.replace("http://", "https://") for cors_origin in CORS_ALLOWED_ORIGINS
] + CORS_ALLOWED_ORIGINS

# HTTPS settings
SESSION_COOKIE_SECURE = config("SSL_CERTIFICATE", default=True, cast=bool)
CSRF_COOKIE_SECURE = config("SSL_CERTIFICATE", default=True, cast=bool)
SECURE_SSL_REDIRECT = config("SSL_CERTIFICATE", default=True, cast=bool)

# HSTS settings
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_PRELOAD = config("SSL_CERTIFICATE", default=True, cast=bool)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SSL_CERTIFICATE", default=True, cast=bool)

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

# Logging
if config("LOGGING", default=True, cast=bool):
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "file": {
                "level": config("LOG_LEVEL", default="INFO"),
                "class": "logging.handlers.RotatingFileHandler",
                "filename": config("LOG_FILE", default="/var/log/django/django.log"),
                "maxBytes": 1024 * 1024 * 5,  # 5 MB
                "backupCount": 5,
                "formatter": "verbose",
                "delay": True,  # Don't create the file until it's needed
            },
        },
        "loggers": {
            "django": {
                "handlers": ["file"],
                "level": config("LOG_LEVEL", default="INFO"),
                "propagate": True,
            },
        },
    }
