# Generated by Django 5.2.9 on 2025-12-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photograph", "0005_remove_photograph_image_photograph_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the album", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the album"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the album was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the album was last updated",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Photographs in this album",
                        related_name="albums",
                        to="photograph.photograph",
                    ),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="album_album_name_2a676e_idx")
                ],
            },
        ),
    ]
