"""Storage adapter contract used by the organizer."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import BinaryIO, Iterable, Protocol

from .domain import MediaObject, StorageCapabilities


class StorageAdapter(Protocol):
    adapter_id: str

    def list_objects(self, path: str) -> Iterable[MediaObject]: ...

    def get_object_info(self, path: str) -> MediaObject: ...

    def open_read(self, path: str) -> AbstractContextManager[BinaryIO]: ...

    def ensure_directory(self, path: str) -> None: ...

    def copy(self, source: str, destination: str) -> None: ...

    def move(self, source: str, destination: str) -> None: ...

    def delete(self, path: str) -> None: ...

    def exists(self, path: str) -> bool: ...

    def get_capabilities(self) -> StorageCapabilities: ...

    def healthcheck(self) -> None: ...
