# Generated by Django 5.2.15 on 2026-09-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DuplicateGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("size", models.BigIntegerField()),
                ("paths", models.JSONField(default=list)),
                ("wasted_bytes", models.BigIntegerField(default=0)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-wasted_bytes"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("adapter", models.CharField(default="local", max_length=50)),
                ("source", models.TextField()),
                ("destination", models.TextField()),
                (
                    "pattern",
                    models.CharField(default="%Y/%YQ%Q/%Y%M%D", max_length=255),
                ),
                ("quarantine", models.TextField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("copy", "Copy"), ("move", "Move")],
                        default="move",
                        max_length=10,
                    ),
                ),
                (
                    "adapter_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret options and names of environment variables containing secrets",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="organizer.organizerconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("source", models.TextField()),
                ("destination", models.TextField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=512)),
                ("capture_date", models.DateTimeField(blank=True, null=True)),
                ("date_source", models.CharField(blank=True, max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="organizer.organizerjob",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="organizer_o_status_b70aaf_idx"
                    ),
                    models.Index(
                        fields=["source"], name="organizer_o_source_648070_idx"
                    ),
                ],
            },
        ),
    ]
