# Generated by Django 5.2.17 on 2026-09-30 09:50

import organizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerconfiguration",
            name="collision",
            field=models.CharField(
                choices=[
                    ("suffix", "Suffix"),
                    ("fail", "Fail"),
                    ("quarantine", "Quarantine"),
                ],
                default="suffix",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="date_priority",
            field=models.JSONField(default=organizer.models.default_date_priority),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="day_starts_at",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="duplicate_detection",
            field=models.CharField(default="size_then_hash", max_length=30),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="include_first",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="media_extensions",
            field=models.JSONField(default=organizer.models.default_media_extensions),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="process_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="retry",
            field=models.JSONField(default=organizer.models.default_retry),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="scan_interval_seconds",
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="stability",
            field=models.JSONField(default=organizer.models.default_stability),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="organizerconfiguration",
            name="workers",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
