# Generated by Django 5.2.17 on 2026-09-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0002_organizerconfiguration_collision_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizerconfiguration",
            options={
                "permissions": [
                    ("operate_organizer", "Can run destructive PhotoChart operations")
                ]
            },
        ),
    ]
