# Generated by Django 5.2.17 on 2026-09-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0004_organizerjob_cancel_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicategroup",
            name="configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_groups",
                to="organizer.organizerconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="organizerjob",
            name="source_paths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organizeroperation",
            name="catalog_status",
            field=models.CharField(default="not_applicable", max_length=30),
        ),
        migrations.CreateModel(
            name="DuplicateScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_scans",
                        to="organizer.organizerconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="duplicategroup",
            name="scan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="organizer.duplicatescan",
            ),
        ),
    ]
