# Generated by Django 5.2.9 on 2025-12-28 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        blank=True,
                        help_text="MD5 hash of the photo file (32 characters)",
                        max_length=32,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hash must be a 32-character hexadecimal string",
                                regex="^[a-f0-9]{32}$",
                            )
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image file for the photograph",
                        null=True,
                        upload_to="photographs/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the photograph record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the photograph record was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photograph",
                "verbose_name_plural": "Photographs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["hash"], name="photograph__hash_98d696_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Full path to the photo file", max_length=2048
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        help_text="Device identifier where the photo is located",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the path record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the path record was last updated",
                    ),
                ),
                (
                    "photograph",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated photograph (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paths",
                        to="photograph.photograph",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Path",
                "verbose_name_plural": "Photo Paths",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["path"], name="photograph__path_2db37b_idx"),
                    models.Index(
                        fields=["device"], name="photograph__device_220883_idx"
                    ),
                    models.Index(
                        fields=["photograph"], name="photograph__photogr_288a63_idx"
                    ),
                ],
                "unique_together": {("path", "device")},
            },
        ),
    ]
