# Generated by Django 5.2.9 on 2025-12-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="time",
            field=models.DateTimeField(
                blank=True,
                help_text="Photograph time extracted from EXIF metadata (when the photo was taken)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photopath",
            name="file_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="File creation timestamp from the filesystem",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photopath",
            name="file_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="File modification timestamp from the filesystem",
                null=True,
            ),
        ),
    ]
