# Generated by Django 5.2.9 on 2025-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0002_photograph_time_photopath_file_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="has_errors",
            field=models.BooleanField(
                default=False,
                help_text="True if any error occurred during image creation or data reading",
            ),
        ),
    ]
