# Generated by Django 5.2.9 on 2025-12-29 19:14

import photograph.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0003_photograph_has_errors"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="model",
            field=models.CharField(
                blank=True,
                help_text="Camera model extracted from EXIF metadata",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image file for the photograph",
                null=True,
                upload_to=photograph.models.photograph_upload_path,
            ),
        ),
    ]
