# Generated by Django 5.2.9 on 2025-12-30 18:46

import photograph.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0004_photograph_model_alter_photograph_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photograph",
            name="image",
        ),
        migrations.AddField(
            model_name="photograph",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail file for the photograph",
                null=True,
                upload_to=photograph.models.photograph_upload_path,
            ),
        ),
    ]
