# Generated by Django 5.2.9 on 2026-01-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0005_remove_photograph_image_photograph_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopath",
            name="size",
            field=models.BigIntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="photopath",
            name="path",
            field=models.CharField(
                help_text="Path to the photo file. For mounted devices, this is relative to the mount point. For root filesystem, this is an absolute path.",
                max_length=2048,
            ),
        ),
    ]
