# Generated by Django 5.2.9 on 2026-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0006_photopath_size_alter_photopath_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopath",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="Filename extracted from the path (the last component of the path)",
                max_length=255,
                null=True,
            ),
        ),
    ]
