# Generated by Django 5.2.9 on 2026-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0007_photopath_filename"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="photograph",
            index=models.Index(fields=["time"], name="photograph__time_a44f56_idx"),
        ),
    ]
